github:
  repositories:
    - repository: ebullient/monster-combat
    - repository: ebullient/pockets-cli
    - repository: ebullient/fc5-convert-cli
    - repository: ebullient/json5e-convert-cli
    - repository: ebullient/obsidian-snippetor
    - repository: ebullient/obsidian-task-collector
    - repository: ebullient/obsidian-theme-ebullientworks
    - repository: quarkusio/quarkus
      labels:
        - area/metrics
        - area/devtools
        - area/cli
        - area/documentation
      hide-labels:
        - pinned
        - "area/.*"
    - repository: quarkiverse/quarkus-micrometer-registry
